### ISSUE TITLE
customizeUI是否支援color?

### ISSUE THREAD

**Issue by osfans** [EasyIME/PIME#160]
目前準備移植[librime](https://github.com/rime/weasel)到pime，它的windows候選界面支援如下設定：
```yaml
    text_color: 0xffe8ca
    candidate_text_color: 0xfff8ee
    back_color: 0x8b4e01
    border_color: 0x8b4e01
    hilited_text_color: 0xfff8ee
    hilited_back_color: 0x8b4e01
    hilited_candidate_text_color: 0x7ffeff
    hilited_candidate_back_color: 0xa95e01
    comment_text_color: 0xc69664
```
