### ISSUE TITLE
中州韻的倉頡五碼有支援反查或是類似的輔助功能嗎

### ISSUE THREAD

**Issue by jfhsu** [EasyIME/PIME#243]
一般倉頡如果打不出字，可以打字首外加萬用字元，
不曉得中州韻的倉頡有沒有類似的功能，畢竟有時會遇到拆不出來的字

**Comment by osfans** [comment]
預設是pinyin反查，先打`引導，然後打pinyin即可。
也可修改成其他反查方案，需要修改reverse_lookup段
https://github.com/rime/brise/blob/master/cangjie/cangjie5.schema.yaml#L80
```yaml
reverse_lookup:
  dictionary: luna_pinyin
  prism: luna_quanpin
  prefix: "`"
  suffix: "'"
  tips: 〔拼音〕
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/
  comment_format:
    - "xlit|abcdefghijklmnopqrstuvwxyz|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符|"
```

**Comment by jfhsu** [comment]
只需要改下面兩行就可以了嗎

> reverse_lookup:
>   dictionary: bopomofo_tw
>   prism: bopomofo_tw

**Comment by osfans** [comment]
具體你可以參考bopomofo_tw.schema.yaml中的translator段
他跟地球拼音共用的帶聲調的字典

```yaml
  dictionary: terra_pinyin
  prism: bopomofo_tw
  preedit_format:
    - "xlit|1qaz2wsxedcrfv5tgbyhnujm8ik,9ol.0p;/- 6347'|ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦˉˊˇˋ˙ |"
```

**Comment by jfhsu** [comment]
我的改法如下, 但按了 prefix ' 後,什麼都沒有, 不知道哪邊miss掉了...

```
reverse_lookup:
  dictionary: bopomofo_tw
  prism: bopomofo_tw
  prefix: "`"
  suffix: "'"
  tips: 〔注音〕
  preedit_format:
    - "xlit|1qaz2wsxedcrfv5tgbyhnujm8ik,9ol.0p;/- 6347'|ㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄗㄘㄙㄧㄨㄩㄚㄛㄜㄝㄞㄟㄠㄡㄢㄣㄤㄥㄦˉˊˇˋ˙ |"
  comment_format:
    - "xlit|abcdefghijklmnopqrstuvwxyz|日月金木水火土竹戈十大中一弓人心手口尸廿山女田難卜符|"
```
