### ISSUE TITLE
1.1版本如何修改配色方案？

### ISSUE THREAD

**Issue by laubonghaudoi** [EasyIME/PIME#443]
尝试过在`default.yaml`和`PIME.yaml`中添加配色方案代码均无效，新建`default.custom.yaml`也无效，应该如何修改界面配色？

**Comment by abelage** [comment]
PIME.yaml
在这个里面改了有效的。

**Comment by osfans** [comment]
還沒有合併到PIME。所以暫時只能先在PRIME上使用。

**Comment by laubonghaudoi** [comment]
@abelage 请问怎么改？能不能发段示例代码，谢谢了！

**Comment by ernsky** [comment]
@laubonghaudoi 下面是我的PIME.YAML文件

`  aqua:
    name: 碧水／Aqua
    author: 佛振 <chen.sst@gmail.com>
    corner_radius: 7 #圓角
    border_height: 10
    border_width: 10
    back_color: 0x362b00 #背景色
    candidate_text_color: 0x969483 #候選字顏色
    hilited_candidate_back_color: 0x362b00 #高亮候選字背景色
    hilited_candidate_text_color: 0xffffff #高亮候選字顏色
    hilited_comment_text_color: 0x362b00 #註解文字高亮
    hilited_text_color: 0x98a12a #for Weasel?
    text_color: 0x009985 #for Weasel?
    font_face: "Hiragino Sans GB, PingFangSC-Regular" #字體
    line_spacing: 5 #行距
    label_font_face: "Hiragino Sans GB" #編號字體
    label_font_point: 18 #編號字號`

**Comment by ernsky** [comment]
@laubonghaudoi 下面是我的PIME.YAML文件

> `  aqua:
    name: 碧水／Aqua
    author: 佛振 <chen.sst@gmail.com>
    corner_radius: 7 #圓角
    border_height: 10
    border_width: 10
    back_color: 0x362b00 #背景色
    candidate_text_color: 0x969483 #候選字顏色
    hilited_candidate_back_color: 0x362b00 #高亮候選字背景色
    hilited_candidate_text_color: 0xffffff #高亮候選字顏色
    hilited_comment_text_color: 0x362b00 #註解文字高亮
    hilited_text_color: 0x98a12a #for Weasel?
    text_color: 0x009985 #for Weasel?
    font_face: "Hiragino Sans GB, PingFangSC-Regular" #字體
    line_spacing: 5 #行距
    label_font_face: "Hiragino Sans GB" #編號字體
    label_font_point: 18 #編號字號
`

**Comment by ernsky** [comment]
@laubonghaudoi 
下面是我的PIME.YAML文件
  aqua:
    name: 碧水／Aqua
    author: 佛振 <chen.sst@gmail.com>
    corner_radius: 7 #圓角
    border_height: 10
    border_width: 10
    back_color: 0x362b00 #背景色
    candidate_text_color: 0x969483 #候選字顏色
    hilited_candidate_back_color: 0x362b00 #高亮候選字背景色
    hilited_candidate_text_color: 0xffffff #高亮候選字顏色
    hilited_comment_text_color: 0x362b00 #註解文字高亮
    hilited_text_color: 0x98a12a #for Weasel?
    text_color: 0x009985 #for Weasel?
    font_face: "Hiragino Sans GB, PingFangSC-Regular" #字體
    line_spacing: 5 #行距
    label_font_face: "Hiragino Sans GB" #編號字體
    label_font_point: 18 #編號字號

**Comment by laubonghaudoi** [comment]
@ernsky 我在`PIME.yaml`的开头加入以下代码，重新部署后没有任何区别
```yaml
style:
  #color_scheme: aqua
  font_face: "Microsoft YaHei"
  font_point: 12
  inline_preedit: composition #composition, preview, input, false
  display_tray_icon: true
  candidate_format: "{0} {1}" #0-candidate, 1-comment
  candidate_per_row: 1
  candidate_use_cursor: true
  soft_cursor: false
  menu_opencc: "" #tw2s.json, t2s.json
  candidate_text_color: 0xFFFFFF
  comment_text_color: 0xFFFFFF
  back_color: 0x362b00 #背景色
  candidate_text_color: 0x969483 #候選字顏色
  hilited_candidate_back_color: 0x362b00 #高亮候選字背景色
  hilited_candidate_text_color: 0xffffff #高亮候選字顏色
  hilited_comment_text_color: 0x362b00 #註解文字高亮
  hilited_text_color: 0x98a12a #for Weasel?
  text_color: 0x009985 #for Weasel?
```
另外，请问如何把竖排显示改为横排显示？
